# Generated by Django 5.0.2 on 2024-04-25 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NgoBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=25, null=True)),
                ('asha_id', models.CharField(max_length=25, null=True)),
                ('health_center', models.CharField(max_length=25, null=True)),
                ('mobile_no', models.IntegerField(null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('blood_grp', models.CharField(max_length=5, null=True)),
                ('aadhar_no', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('office_address', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
