# Generated by Django 5.0.2 on 2024-05-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashaease', '0006_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='added_child_cound',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='added_no_of_members',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='added_patients_cound',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='added_pregnant_cound',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='child_cound',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='no_of_members',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='patients_cound',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='pregnant_cound',
            field=models.IntegerField(default=0),
        ),
    ]
