# Generated by Django 5.0.2 on 2024-05-13 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashaease', '0007_alter_house_added_child_cound_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('age', models.IntegerField(default=0)),
                ('qualification', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=30)),
                ('habit', models.BooleanField(default=False)),
                ('habittype', models.CharField(max_length=20, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='ashaease.house')),
            ],
        ),
    ]
