# Generated by Django 5.0.2 on 2024-05-13 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashaease', '0008_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashaease.house'),
        ),
    ]
