# Generated by Django 5.0.2 on 2024-05-13 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashaease', '0009_alter_members_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.BooleanField(default=False)),
                ('threemonth', models.BooleanField(default=False)),
                ('sixmonth', models.BooleanField(default=False)),
                ('oneyear', models.BooleanField(default=False)),
                ('fiveyear', models.BooleanField(default=False)),
                ('tenyear', models.BooleanField(default=False)),
                ('fifteenyear', models.BooleanField(default=False)),
                ('reason', models.TextField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashaease.members')),
            ],
        ),
    ]
