# Generated by Django 5.0.2 on 2024-05-14 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashaease', '0011_pregnant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_details', models.TextField()),
                ('pain', models.BooleanField(default=False)),
                ('disease', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashaease.members')),
            ],
        ),
    ]
